/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics */

#ifndef _Included_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
#define _Included_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_initFieldIDs(JNIEnv *env, jclass cls) {

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawLine
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawLine
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    fillRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_fillRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawRect
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawRect
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawRoundRect
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawRoundRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    fillRoundRect
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_fillRoundRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    fillArc
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_fillArc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawArc
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawArc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawString
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawString
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawSubstring
 * Signature: (Ljava/lang/String;IIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawSubstring
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawChar
 * Signature: (CIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawChar
  (JNIEnv *, jobject, jchar, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawChars
 * Signature: ([CIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawChars
  (JNIEnv *, jobject, jcharArray, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    fillTriangle
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_fillTriangle
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    doCopyArea
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_doCopyArea
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    drawRGB
 * Signature: ([IIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_drawRGB
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    getDisplayColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_getDisplayColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    render
 * Signature: (Lorg/thenesis/microbackend/ui/graphics/toolkit/gxj/GXJImage;III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_render
  (JNIEnv *, jobject, jobject, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    renderRegion
 * Signature: (Lorg/thenesis/microbackend/ui/graphics/toolkit/gxj/GXJImage;IIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_renderRegion
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics
 * Method:    getPixel
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJGraphics_getPixel
  (JNIEnv *, jobject, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
