/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont */

#ifndef _Included_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
#define _Included_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
#ifdef __cplusplus
extern "C" {
#endif
#undef org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_FONT_STATIC_TEXT
#define org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_FONT_STATIC_TEXT 0L
#undef org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_FONT_INPUT_TEXT
#define org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_FONT_INPUT_TEXT 1L
/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
 * Method:    charWidth
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_charWidth
  (JNIEnv *, jobject, jchar);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
 * Method:    charsWidth
 * Signature: ([CII)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_charsWidth
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
 * Method:    stringWidth
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_stringWidth
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
 * Method:    substringWidth
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_substringWidth
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_thenesis_microbackend_ui_graphics_toolkit_gxj_GXJFont_init
  (JNIEnv *, jobject, jint, jint, jint);

void GXJFont_getFontType(JNIEnv *env, jobject obj, jint* face, jint* style, jint* size);

#ifdef __cplusplus
}
#endif
#endif
